services:
  php:
    build: .
    environment:
      - DB_HOSTNAME
      - DB_PORT
      - DB_USERNAME
      - DB_PASSWORD
      - DB_DATABASE
      - EMAIL_NAME
      - EMAIL_PASS
      - BASE_URL
    volumes:
      - ./:/var/www/html
